# Generated by Django 4.1 on 2022-08-14 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('book_official_link', models.TextField()),
                ('grade', models.CharField(choices=[('ten', 'tenth'), ('ele', 'eleventh'), ('twe', 'twelfth'), ('alg', 'all grades'), ('oth', 'other')], max_length=3)),
                ('lesson', models.CharField(choices=[('calculus', 'calculus'), ('physics', 'physics'), ('chemistry', 'chemistry'), ('geometry', 'geometry'), ('statistics and probability', 'statistics and probability'), ('discrete math', 'discrete math'), ('biology', 'biology'), ('persian', 'persian'), ('arabic', 'arabic'), ('english', 'english'), ('religion and life', 'religion and life'), ('other', 'other')], max_length=30)),
                ('year', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('time_created', models.TimeField(auto_now_add=True)),
                ('is_active', models.BooleanField()),
                ('book_cover', models.ImageField(blank=True, upload_to='book_covers/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
