# Generated by Django 4.1 on 2022-08-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_need_or_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='need_or_add',
            field=models.CharField(choices=[('need', 'needed'), ('add', 'added')], max_length=5),
        ),
    ]
