# Generated by Django 4.1 on 2022-08-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='major',
            field=models.CharField(blank=True, choices=[('riazi', 'riazi'), ('tajrobi', 'tajrobi'), ('ensani', 'ensani'), ('general', 'general'), ('other', 'other')], max_length=10),
        ),
    ]
