# Generated by Django 4.1 on 2022-08-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='major',
            field=models.CharField(choices=[('riazi', 'riazi'), ('tajrobi', 'tajrobi'), ('ensani', 'ensani'), ('general', 'general'), ('other', 'other')], max_length=10),
        ),
    ]
