# Generated by Django 4.1 on 2022-08-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_official_link',
            field=models.CharField(max_length=350),
        ),
    ]
