# Generated by Django 4.1 on 2022-08-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_book_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_official_link',
            field=models.TextField(),
        ),
    ]
