# Generated by Django 4.1 on 2022-08-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_book_book_official_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='grade_en',
            field=models.CharField(choices=[('ten', 'دهم'), ('ele', 'یازدهم'), ('twe', 'دوازدهم'), ('alg', 'جامع همه پایه ها'), ('oth', 'دیگر')], max_length=3, null=True, verbose_name='پایه'),
        ),
        migrations.AddField(
            model_name='book',
            name='grade_fa',
            field=models.CharField(choices=[('ten', 'دهم'), ('ele', 'یازدهم'), ('twe', 'دوازدهم'), ('alg', 'جامع همه پایه ها'), ('oth', 'دیگر')], max_length=3, null=True, verbose_name='پایه'),
        ),
        migrations.AddField(
            model_name='book',
            name='lesson_en',
            field=models.CharField(choices=[('calculus', 'حسابان'), ('physics', 'فیزیک'), ('chemistry', 'شیمی'), ('geometry', 'هندسه'), ('statistics and probability', 'آمار و احتمال'), ('discrete math', 'ریاضیات گسسته'), ('biology', 'زیست'), ('persian', 'فارسی'), ('arabic', 'عربی'), ('english', 'انگلیسی'), ('religion and life', 'دین و زندگی'), ('other', 'دیگر')], max_length=30, null=True, verbose_name='درس'),
        ),
        migrations.AddField(
            model_name='book',
            name='lesson_fa',
            field=models.CharField(choices=[('calculus', 'حسابان'), ('physics', 'فیزیک'), ('chemistry', 'شیمی'), ('geometry', 'هندسه'), ('statistics and probability', 'آمار و احتمال'), ('discrete math', 'ریاضیات گسسته'), ('biology', 'زیست'), ('persian', 'فارسی'), ('arabic', 'عربی'), ('english', 'انگلیسی'), ('religion and life', 'دین و زندگی'), ('other', 'دیگر')], max_length=30, null=True, verbose_name='درس'),
        ),
        migrations.AddField(
            model_name='book',
            name='major_en',
            field=models.CharField(choices=[('riazi', 'ریاضی فیزیک'), ('tajrobi', 'علوم تجربی'), ('ensani', 'انسانی'), ('general', 'عمومی'), ('other', 'دیگر')], max_length=10, null=True, verbose_name='رشته'),
        ),
        migrations.AddField(
            model_name='book',
            name='major_fa',
            field=models.CharField(choices=[('riazi', 'ریاضی فیزیک'), ('tajrobi', 'علوم تجربی'), ('ensani', 'انسانی'), ('general', 'عمومی'), ('other', 'دیگر')], max_length=10, null=True, verbose_name='رشته'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher_en',
            field=models.CharField(max_length=100, null=True, verbose_name='انتشارات'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher_fa',
            field=models.CharField(max_length=100, null=True, verbose_name='انتشارات'),
        ),
        migrations.AddField(
            model_name='book',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='book',
            name='title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(blank=True, upload_to='book_covers/', verbose_name='تصویر جلد'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_official_link',
            field=models.TextField(verbose_name='لینک کتاب در صفحه رسمی'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, verbose_name='متن مقاله'),
        ),
        migrations.AlterField(
            model_name='book',
            name='grade',
            field=models.CharField(choices=[('ten', 'دهم'), ('ele', 'یازدهم'), ('twe', 'دوازدهم'), ('alg', 'جامع همه پایه ها'), ('oth', 'دیگر')], max_length=3, verbose_name='پایه'),
        ),
        migrations.AlterField(
            model_name='book',
            name='lesson',
            field=models.CharField(choices=[('calculus', 'حسابان'), ('physics', 'فیزیک'), ('chemistry', 'شیمی'), ('geometry', 'هندسه'), ('statistics and probability', 'آمار و احتمال'), ('discrete math', 'ریاضیات گسسته'), ('biology', 'زیست'), ('persian', 'فارسی'), ('arabic', 'عربی'), ('english', 'انگلیسی'), ('religion and life', 'دین و زندگی'), ('other', 'دیگر')], max_length=30, verbose_name='درس'),
        ),
        migrations.AlterField(
            model_name='book',
            name='major',
            field=models.CharField(choices=[('riazi', 'ریاضی فیزیک'), ('tajrobi', 'علوم تجربی'), ('ensani', 'انسانی'), ('general', 'عمومی'), ('other', 'دیگر')], max_length=10, verbose_name='رشته'),
        ),
        migrations.AlterField(
            model_name='book',
            name='need_or_add',
            field=models.CharField(choices=[('need', 'درخواست دادن'), ('add', 'اضافه کردن')], max_length=5, verbose_name='نوع '),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=100, verbose_name='انتشارات'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(verbose_name='سال چاپ'),
        ),
    ]
