# Generated by Django 4.1 on 2022-08-24 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_book_grade_en_book_grade_fa_book_lesson_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publisher_en',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher_fa',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title_fa',
        ),
    ]
