# Generated by Django 4.1 on 2022-08-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_address_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='سن'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='biography',
            field=models.TextField(blank=True, verbose_name='درباره خود'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'آقا'), ('female', 'خانم')], max_length=10, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=12, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(blank=True, upload_to='profiles/', verbose_name='عکس پروفایل'),
        ),
    ]
