# Generated by Django 4.1 on 2022-08-14 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('lesson', models.CharField(choices=[('calculus', 'calculus'), ('physics', 'physics'), ('chemistry', 'chemistry'), ('geometry', 'geometry'), ('statistics and probability', 'statistics and probability'), ('discrete math', 'discrete math'), ('biology', 'biology'), ('persian', 'persian'), ('arabic', 'arabic'), ('english', 'english'), ('religion and life', 'religion and life'), ('other', 'other')], default=('other', 'other'), max_length=30)),
                ('grade', models.CharField(choices=[('ten', 'tenth'), ('ele', 'eleventh'), ('twe', 'twelfth'), ('alg', 'all grades'), ('oth', 'other')], default=('oth', 'other'), max_length=3)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_lastedit', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('post_cover', models.ImageField(blank=True, upload_to='post_covers/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('recommend', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='blog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
