# Generated by Django 4.1 on 2022-08-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='recommend',
            field=models.BooleanField(default=True, verbose_name='پیشنهاد کردن'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='متن نظر'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(verbose_name='متن نظر'),
        ),
        migrations.AlterField(
            model_name='post',
            name='grade',
            field=models.CharField(choices=[('ten', 'دهم'), ('ele', 'یازدهم'), ('twe', 'دوازدهم'), ('alg', 'جامع همه پایه ها'), ('oth', 'دیگر')], default=('oth', 'دیگر'), max_length=3, verbose_name='پایه'),
        ),
        migrations.AlterField(
            model_name='post',
            name='lesson',
            field=models.CharField(choices=[('calculus', 'حسابان'), ('physics', 'فیزیک'), ('chemistry', 'شیمی'), ('geometry', 'هندسه'), ('statistics and probability', 'آمار و احتمال'), ('discrete math', 'ریاضیات گسسته'), ('biology', 'زیست'), ('persian', 'فارسی'), ('arabic', 'عربی'), ('english', 'انگلیسی'), ('religion and life', 'دین و زندگی'), ('other', 'دیگر')], default=('other', 'دیگر'), max_length=30, verbose_name='درس'),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.TextField(verbose_name='لینک کتاب در صفحه رسمی'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_cover',
            field=models.ImageField(blank=True, upload_to='post_covers/', verbose_name='کاور مقاله'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publisher',
            field=models.CharField(max_length=200, verbose_name='انتشارات'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
    ]
